import React from 'react';

import VirtualFit1 from "../../assets/images/vrstore_360icon.jpg";
import VirtualFit2 from "../../assets/images/virtaul2.JPEG";
import VirtualFit3 from "../../assets/images/virtual3.jpeg";
import VirtualFit4 from "../../assets/images/virtual4.gif";
import VirtualFit5 from "../../assets/images/virtual5.png";
import VirtualFit6 from "../../assets/images/virtual6.jpg";

const Card = ({title, desc, img}) => {
    return (
        <div className='flex flex-col gap-6 items-center p-5'>
            <img className='rounded-xl  max-h-56' src={img} alt="img" />
            <h2 className='text-4xl text-center anton'>{title}</h2>
            <p className='text-center'>{desc}</p>
        </div>
    )
}


const VirtualFit = () => {
  return (
    <div className='container max-w-7xl mx-auto text-white py-16'>
        <h1 className='anton text-6xl'>VIRTUAL FIT:</h1>
        <h1 className='anton text-6xl text-red-600/40'>THE FUTURE OF FASHION</h1>
        
        <div className='mt-10'>
            <p className='h-full text-[24px] w-5/6 mx-auto text-center flex items-center justify-center'>Virtual Fit is not just a fashion app, but a lifestyle that makes the clothing experience more interactive and enjoyable. Join this platform that brings fashion together with augmented reality, enrich your wardrobe and discover new ways to share your passion for fashion!</p>
        </div>

        <h1 className='anton text-5xl mt-16'>FEATURES:</h1>
        <p>Virtual Fit brings a breath of fresh air to fashion and clothing. Offering an augmented reality experience, this mobile application offers users an experience beyond online shopping. It includes many features from trying on clothing products on a virtual platform to creating custom animations and sharing fashion with social media filters. Here are the remarkable features of Virtual Fit:</p>

        <div className='grid grid-cols-3 gap-10 mt-10'>
            <Card img={VirtualFit1} title="Virtual Store Experience" desc="Users have the chance to virtually try on the products of the stores you have an agreement with. In this way, they can see how the products will look on their real bodies. At the same time, buyers can easily make purchases by being directed to the relevant page with the appropriate size selection and product information." />
            <Card img={VirtualFit2} title="Animations and Social Shares" desc="Special events offer the opportunity to see the clothes on the models with realistic animations. You can get information about the outfits enriched with animations instantly and you can record these moments and share them on social media. This makes the fashion world more interactive and fun." />
            <Card img={VirtualFit3} title="Outfit Suggestions and Personalized Content" desc="Users can receive daily outfit suggestions generated by artificial intelligence based on the outfits they have purchased and saved on the app. This feature allows you to be inspired for your style every day." />
            <Card img={VirtualFit4} title="Create and Share Your Animations" desc="You can buy your own animations on the outfits defined in the app. Using these animations, you can make your outfits more personal and fun. It also allows you to create interaction between fashionistas by allowing others to discover your animations." />
            <Card img={VirtualFit5} title="Connected with Metaverse and Joint NFT Generation" desc="Users can dress their metaverse characters in the outfits they choose through Virtual Fit. This is a new and fun way to express your own style in the virtual world. The platform allows contracted stores to showcase their products in a virtual showroom environment in a real store atmosphere. Users can walk around these showrooms in the metaverse to see and experience the products in a realistic way. Users can design clothing combinations for collaborative projects, create them as NFTs and offer them for sale. This turns collective creativity into an income-generating path." />
            <Card img={VirtualFit6} title="Events, Competitions and Prizes" desc="Various small prize contests, events, polls and sweepstakes are organized within the app. These events bring your community together and provide more enjoyment for fashionistas." />
        </div>
    </div>
  )
}

export default VirtualFit